fullnameOverride: "gotin-mobile-nanjing"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80
jxRequirements:
  ingress:
    namespaceSubDomain: "."
    domain: "stag.gotin.online"
    kind: ingress
    tls:
      enabled: true
      secretName: acme-gotin-online
image:
  tagSuffix: stag
