export declare const ConfigAvatarMesh: {
    __root__: number;
    Basics_Body: number;
    Basics_Mouth: number;
    Basics_Pants_1: number;
    Basics_Pants_2: number;
    Basics_Shirt_1: number;
    Basics_Shirt_2: number;
    Basics_Shoes_1: number;
    Boy_Eyebrow: number;
    Boy_Eyes: number;
    Boy_Hair_1: number;
    Boy_Hair_2: number;
    Boy_Hair_3: number;
    Boy_Hair_4: number;
    Boy_Hair_5: number;
    Boy_Nose: number;
    Girl_Eyes: number;
    Girl_Hair_1: number;
    Girl_Hair_2: number;
    Girl_Hair_3: number;
    Girl_Hair_4: number;
    Girl_Hair_5: number;
    Girl_Nose: number;
};
