import { AvatarInterface } from '../../../modules/avatar/v2/avatar_interface';
import * as BABYLON from '@babylonjs/core';
import { AnimationStateMachine } from './animation_state_machine';
import { ControllerAttribute } from './controllerAttribute';
export declare class PcController {
    isEnabledCameraRotation: boolean;
    private _scene;
    private _camera;
    private _player;
    private _tempQuat;
    private _locateBox;
    private _tempRotation;
    private keyState;
    private keyTimeState;
    private _keyDirection;
    private _moveDirection;
    private _moveTarget;
    private _targetDirection;
    private _targetPosition;
    private _targetPoint;
    private _initPosition;
    private _targetBall;
    private _targetDistance;
    private _speed;
    private _pointerMesh;
    private _controllerAttribute;
    private _pointerMeshTime;
    private _leftMouseDown;
    private _leftMouseMove;
    private _pointerDownTime;
    private _rayCheckTime;
    private _lastFrameTime;
    private _animationStateMachine?;
    private _pointerObservable?;
    private _keyboardObservable?;
    constructor(scene: BABYLON.Scene, camera: BABYLON.ArcRotateCamera, player: AvatarInterface, locateBox: BABYLON.Mesh, animationStateMachine?: AnimationStateMachine, config?: Partial<ControllerAttribute>);
    attachPlayer(): void;
    detachPlayer(): void;
    private _keydownHandler;
    private _clickHandler;
    private _updateTargetByKeyboard;
    private _updateTargetByClick;
    _clearTarget(): void;
    private _checkIfCollision;
    update: () => void;
}
