{{- if .Values.jxRequirements.ingress.domain }}
apiVersion: {{ .Values.jxRequirements.ingress.apiVersion }}
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  name: {{ .Values.service.name }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path | default "/" }}
        backend:
          service:
            name: {{ .Values.service.name }}
            port: 
              number: 80
        pathType: ImplementationSpecific
    host: "{{ .Values.jxRequirements.ingress.domainPrefix }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}"

  {{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
    - "{{ .Values.jxRequirements.ingress.domainPrefix }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}"
    {{- if and (hasKey .Values.jxRequirements.ingress.tls "secretName") (.Values.jxRequirements.ingress.tls.secretName) }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
    {{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "jx/tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
    {{- else }}
    secretName: "jx/tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
    {{- end }}
  {{- end }}
{{- end }}
